---
editor_options: 
  markdown: 
    wrap: 72
---

# Next Generation Matrix

## Introduction to the Chapter

This chapter describes in depth the use of a Next Generation Matrix
(NGM). This tool is used to calculate the $R_0$ value \@ref(def:R0).
Using the NGM achieves this this for multi-compartmental models, such as
SEIR (Refer back to Chapter 2), by linearizing the system of
differential equations around the Disease-Free Equilibrium (DFE)
\@ref(def:DFE) and and dividing the flow \@ref(def:Flow) of disease into
what causes new cases and what accounts for everything else that happens
to an infected person. It is also important to mention that these tools are
not limited to specific models and can be used for a variety of models.

## Definining the Parameters

Beginning with X, the vector of disease compartments. For the SEIR
model, $X = \begin{bmatrix} E\\ I\\ \end{bmatrix}$. For the SIR model,
$X = \begin{bmatrix} I \end{bmatrix}$

$$\frac{dX}{dt} = F(x) - V(x)$$

$F(x)$ is a vector of the terms that lead to new infections

$V(x) = V^- (x) -V^+ (x)$ where $V^- (x)$ and $-V^+ (x)$ contain all
other outputs and inputs, respectively, for each disease compartment

### Defining the Disease Free Equilibrium (DFE)

The Disease Free Equilibrium exists when all infected compartments (I and E), are set to 0. i.e. E=0 and I=0.

$$
\begin{align*}
\ \dot{S} &= - \beta SI = 0\\ 
\ \dot{E} &= \beta SI - \delta E = 0 \\
\ \dot{I} &= \delta E - \gamma I = 0\\
\ \dot{R} &= \gamma I = 0\\ 
\end{align*}
$$
At the DFE:

- $\dot{S}$ is true when I=0
- $\dot{E}$ is true when I=0 and E=0
- $\dot{I}$ is true when E=0 and I=0
- $\dot{R}$ is true when I=0

Since there are no infections: $E=I=R=0$
This means that for $N=S+I+E+R$, $N=S$ due to our earlier statements
So at the DFE for the (S,E,I,R) = (N,0,0,0)

This is important for understanding later subsitutions in the Chapter.

## Solving SEIR Model with NGM

Recall: that for the SEIR model the disease compartments are E and I

$\dot{X} = \begin{bmatrix} \dot{E}\\ \dot{I}\\ \end{bmatrix}$

Recall from Ch \_\_:

$$
\begin{align*}
\ \dot{S} &= - \beta SI \\ 
\ \dot{E} &= \beta SI - \delta E \\
\ \dot{I} &= \delta E - \gamma I \\
\ \dot{R} &= \gamma I \\ 
\end{align*}
$$

Insert an tikz image of SEIR compartments here

For the SIR model, $X = \begin{bmatrix} I \end{bmatrix}$

$$
\begin{align*}
\ \dot{X} &= \begin{bmatrix} \dot{E}\\ \dot{I}\\ \end{bmatrix} \\
\ \dot{X} &= \begin{bmatrix} \beta SI - \delta E \\ \delta E - \gamma I \\ \end{bmatrix} \\
\ \dot{X} &= \begin{bmatrix} \beta SI \\ 0 \\ \end{bmatrix} - \left( \begin{bmatrix} \delta E \\ \gamma I \\ \end{bmatrix} - \begin{bmatrix} 0 \\ \delta E \\ \end{bmatrix} \right) \\
\ \dot{X} &= F(x) - ( V^- (x) -V^+ (x) ) \\
\end{align*}
$$

Note that the 0 in
$F(x) = \begin{bmatrix} \beta SI \\ 0 \\ \end{bmatrix}$ exists because
$F$ only considers brand new infected (the flow from $S \rightarrow E$
and not $S \rightarrow I$). I.e. infected, not necessarily infectious.

We separate the equation into components to assist us in our $R_0$
calculations

For further simplicity, let:\
$$
F(x) = \begin{bmatrix} \beta SI \\ 0 \\ \end{bmatrix} = \begin{bmatrix} F_1 \\ F_2 \\ \end{bmatrix} 
$$

Also let:\
$$
V(x) = \begin{bmatrix} \delta E \\ \gamma I - \delta E \\ \end{bmatrix} = \begin{bmatrix} V_1 \\ V_2 \\ \end{bmatrix} 
$$

Find the Jacobians of F(x) and V(x) at the disease free equilibrium
(DFE):

Let the Jacobian of F(x) be **F**.

$$
\boldsymbol{F} = J_F (x) = \begin{bmatrix} 
\frac{\partial F_1}{\partial E} & \frac{\partial F_1}{\partial I} \\
\frac{\partial F_2}{\partial E} & \frac{\partial F_2}{\partial I} \\
\end{bmatrix}
= \begin{bmatrix} 
0 & \beta S \\
0 & 0 \\
\end{bmatrix}
$$

At DFE, $S = 1$

- This is found by our earlier definition of the DFE.
  - At the DFE for (S,E,I,R) = (N,0,0,0)
  - Since Population $"N"=1$ and $S=N$, then $S=1$
- So after subsituting $S=1$:

$$
J_F (x) 
= \begin{bmatrix} 
0 & \beta \\
0 & 0 \\
\end{bmatrix}
$$

Let the Jacobian of V(x) be **V**.

$$
\boldsymbol{V} = J_V (x) = \begin{bmatrix} 
\frac{\partial V_1}{\partial E} & \frac{\partial V_1}{\partial I} \\
\frac{\partial V_2}{\partial E} & \frac{\partial V_2}{\partial I} \\
\end{bmatrix}
= \begin{bmatrix} 
\delta & 0 \\
-\delta & \gamma \\
\end{bmatrix}
$$

Another way to think about it:
$\dot{X} = (f-v) \begin{bmatrix} E \\ I \end{bmatrix} = (f-v)X$

Now find the NGM.

$NGM = \boldsymbol{F} \boldsymbol{V}^{-1}$

The NGM for this is $$
\boldsymbol{F} = \begin{bmatrix} 
0 & \beta \\
0 & 0 \\
\end{bmatrix}
$$

and by the rule: for matrix
$M = \begin{bmatrix} a & b \\ c & d \\ \end{bmatrix}$ the inverse
$M^{-1} = \frac{1}{ad-bc} \begin{bmatrix} d & -b \\ -c & a \\ \end{bmatrix}$

Then for $\boldsymbol{V} ^{-1}$ we get $$
\boldsymbol{V} ^{-1} = \frac{1}{\delta \gamma} \begin{bmatrix} 
\gamma & 0 \\
\delta & \delta \\
\end{bmatrix}
$$

$$
\begin{align*}
\ \boldsymbol{F} \boldsymbol{V} ^{-1} &= \begin{bmatrix} 0 & \beta \\ 0 & 0 \\ \end{bmatrix}
\frac{1}{\delta \gamma} 
\begin{bmatrix} \gamma & 0 \\ \delta & \delta \\ \end{bmatrix} \\
\ &= \begin{bmatrix} 0 & \beta \\ 0 & 0 \\ \end{bmatrix}
\begin{bmatrix} \frac{1}{\delta} & 0 \\ \frac{1}{\gamma} & \frac{1}{\gamma} \\ \end{bmatrix} \\
\ &= \begin{bmatrix} \frac{\beta}{\gamma} & \frac{\beta}{\gamma} \\ 0 & 0 \\ \end{bmatrix} \\
\end{align*}
$$

$R_0$ is the spectral radius of $\ \boldsymbol{F} \boldsymbol{V} ^{-1}$
(i.e. the largest eigenvalue)

$$
det \left( \begin{bmatrix} 
\frac{\beta}{\gamma} - \lambda & \frac{\beta}{\gamma} \\
0 & - \lambda \\
\end{bmatrix} \right)
= - \lambda \left( \frac{\beta}{\gamma} - \lambda \right)
$$

Let $- \lambda \left( \frac{\beta}{\gamma} - \lambda \right) = 0$.

So $\lambda = 0$ and $\lambda = \frac{\beta}{\gamma}$. The latter is the
largest eigenvalue, so $R_0 = \lambda = \frac{\beta}{\gamma}$.

## Solving the SEIR Model with Birth and Death

$$S+E+I+R=N$$
$\mu N$ represents births in the system. 

$\mu$ represents deaths.  

The four differential equations can then be constructed, however for the next generation model we only care about $\dot{E}$ and $\dot{I}$.



\begin{align*}
\dot{S} &= \mu N - \frac{\beta SI}{N} \\
\dot{R} &= \gamma I - \mu R \\

\dot{E} &= \frac{\beta SI}{N} - (\sigma + \mu)E \\
\dot{I} &= \sigma E - (\gamma + \mu)I
\end{align*} 



Next Generation Model: 
$$
\begin{align*}
\dot(x) &= F(x) - V(x) \\
&= \begin{bmatrix} 
\frac{\beta SI}{N} \\ 
0 
\end{bmatrix} - 
\begin{bmatrix}
(\sigma + \mu)E \\
(\gamma + \mu)I - \sigma E
\end{bmatrix}
\end{align*}
$$

The first matrix in the above equation shows F(x) and the second shows
V(x). The Jacobian of $F(x)$ is 
$$
\begin{bmatrix}
0 & \frac{\beta S}{N} \\
0 & 0
\end{bmatrix}
$$ 
And since at the DFE S is equal to N, 
$$
\textbf{F} = \begin{bmatrix} 0 &\beta \\0&0 \end{bmatrix}
$$
The Jacobian of $V(x)$ is 
$$
\textbf{V} = \begin{bmatrix} \sigma + \mu & 0 \\ -\sigma & \gamma + \mu \end{bmatrix}
$$ 
Next gen matrix is 
$$
\begin{align*}
FV^{-1} &= 
\begin{bmatrix}
0 & \beta \\
0 & 0
\end{bmatrix}
\frac{1}{(\sigma + \mu)(\gamma + \mu)}
\begin{bmatrix}
\gamma + \mu & 0 \\
\sigma & \sigma + \mu
\end{bmatrix} \\
&= 
\begin{bmatrix}
\frac{\beta \sigma}{(\sigma + \mu)(\gamma + \mu)} & \frac{\beta}{\gamma + \mu} \\
0 & 0
\end{bmatrix}
\end{align*}
$$

The largest eigenvalue
$\frac{\beta \sigma}{(\sigma + \mu)(\gamma +\mu)} = R_0$

References: [@blackwood2018]
